"""Add user roles and student IDs

Revision ID: 415127fffa64
Revises: d4e8bb30430d
Create Date: 2026-09-14 02:01:41.978005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415127fffa64'
down_revision = 'd4e8bb30430d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=32), server_default='student', nullable=False))
        batch_op.create_index(batch_op.f('ix_users_student_id'), ['student_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_student_id'))
        batch_op.drop_column('role')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
